markdown: kramdown
pygments: true
permalink: /posts/:title
url: warahul.github.io
#baseurl: warahul.github.io    
exclude: [ Gemfile, Gemfile.lock]
description: "Personal blog of Rahul Wadbude."
googleAnalyticsKey: UA-71335999-1
gravatar_url: http://s.gravatar.com/avatar/a7aa9238f45f8960a195611c0e9cfbf6?s=80
author:
  name: Rahul Wadbude
  github: warahul
  linkedin: warahul
  se:
    quant: 6185
    cv: 30815
    mo: 40595
    math: 78654
    overall: 2792935
  bitbucket: warahul
  codeforces: warahul
  facebook: rahul.wadbude.3

research:
  - text: Natural Language Processing
    elements:
      - name: User Bias Removal in Fine Grained Sentiment Analysis
        # url: http://jmlr.org/papers/v14/tulabandhula13a.html
        text: |
         description
      - name: BAT: An Unsupervised Approach for Construction of Domain-Specific Affect Lexicons
        # url: http://jmlr.org/papers/v14/tulabandhula13a.html
        text: |
         description
  - text: Computer Vision
    elements:
      - name: Modifying DPPnet architecture for VQA
        # url: http://jmlr.org/papers/v14/tulabandhula13a.html
        text: |
         description
      - name: Vehicle detection and classification from traffic videos
        # url: http://jmlr.org/papers/v14/tulabandhula13a.html
        text: |
         description
  - text: Machine Learning
    elements:
      - name: Multiple Kernel Learning
        # url: http://jmlr.org/papers/v14/tulabandhula13a.html
        text: |
         description
  - text: Others
    elements:
      - name: Designing Nachos
        # url: http://jmlr.org/papers/v14/tulabandhula13a.html
        text: |
         description
      - name: Designing python3 to x86 compiler
        # url: http://jmlr.org/papers/v14/tulabandhula13a.html
        text: |
         description
unused:
  - name: Googlecode
    url: https://code.google.com/u/112163485814726382683/
