markdown: kramdown
pygments: true
permalink: /posts/:title
url: warahul.github.io
#baseurl: warahul.github.io    
exclude: [ Gemfile, Gemfile.lock]
description: "Personal blog of Rahul Wadbude."
googleAnalyticsKey: UA-71335999-1
gravatar_url: http://s.gravatar.com/avatar/a7aa9238f45f8960a195611c0e9cfbf6?s=80
author:
  name: Rahul Wadbude
  github: warahul
  linkedin: warahul
  se:
    quant: 6185
    cv: 30815
    mo: 40595
    math: 78654
    overall: 2792935
  bitbucket: warahul
  codeforces: warahul
  facebook: rahul.wadbude.3

research:
  - text: Machine Learning applications
    elements:
      - name: Graph Kernels
        # url: http://jmlr.org/papers/v14/tulabandhula13a.html
        text: |
         For the Course Project for the course Learning With Kernels we implemented the graph kernels based upon SVN Vishwanathan's 2010 paper on Graph Kernels . The crux of the project was to compute the similarity of 2 graphs . We implemented the Random Walk Kernel and the Shortest Path Kernel on MATLAB and tested it on protein and enzymes data which can be represented as a graph .     
unused:
  - name: Googlecode
    url: https://code.google.com/u/112163485814726382683/
